### ISSUE TITLE
display number of unlinked extends

### ISSUE THREAD

**Issue by gregovsky** [rah003/neat-tweaks#1]
As a check of errors/typos in "extends" properties and since we have now links when target location exists, will be nice to see how many of them has no link (location doesn't exist), because of typo or because target location was renamed or removed. This number can be just displayed somewhere (bottom line with path, actionbar panel, ...).

Optionally: if this number can be clickable and after click will list (search) all these wrong extends that will be awesome ;)

**Comment by rah003** [comment]
Probably not with just number, but sub view with some stats and links to broken stuff might be doable.

**Comment by rah003** [comment]
Fixed by 3d86db1. Released as part of 2.0.0
