### ISSUE TITLE
"edit template path" issue

### ISSUE THREAD

**Issue by gregovsky** [rah003/neat-tweaks#4]
![magnolia_5](https://cloud.githubusercontent.com/assets/15031941/11528884/c02d5f4e-98e9-11e5-948b-21080585c79e.png)

"edit template path" display for "id" in availableComponents and clicking on it fails (ce 5.4.3)

**Comment by rah003** [comment]
Because id doesn't have template path I presume? :D
What would be expected available? Action disabled or it traverses to nearest component or area higher u p in the hierarchy and let you edit template path for it?

**Comment by gregovsky** [comment]
action "select templateScript" which will add new property "templateScript" if doesn't exist yet or just modify existing one.

**Comment by rah003** [comment]
missing dialog definition for neat-tweaks-developers:editTemplatePath

**Comment by rah003** [comment]
This will not work properly on 5.4.x unless https://jira.magnolia-cms.com/browse/MGNLUI-3725 and/or https://jira.magnolia-cms.com/browse/MGNLUI-3232 are fixed.

**Comment by rah003** [comment]
The action and chooser for the dialog field are committed now, but as mentioned in previous comment that action will not work properly until those Magnolia issues are fixed.
