### ISSUE TITLE
multiple export

### ISSUE THREAD

**Issue by gregovsky** [rah003/neat-tweaks#5]
on 5.3.12 it creates zip with multiple xml files, these files has right name, but are empty and has zero bytes size.

on 5.4.3 doesn't work at all :)

BTW anything for multiple import ? :)

**Comment by rah003** [comment]
Fixed as of 632e69a in 2.x branch (5.4.x compatible)

as for 1.x branch ... necessary fix is similar, but not exactly 1-2-1 back port, so issue is not going to get fixed there unless someone contributes patch.
